apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OB8gT25TAX9K0ryq,iv:6tSqw+ws/9N89CVnN9qUO0DwcUZWXOKAXGZ1tyRyYro=,tag:+9seBjbrJppGGHN/63dsHw==,type:str]
    user: ENC[AES256_GCM,data:g19legoYUlcrdqR6,iv:OgTayAhQx91U1orUOfmWKEofm7abMVxu9HUnnAdGoRU=,tag:4vl1h40t9AfLkpYhjrglyQ==,type:str]
kind: Secret
metadata:
    name: docmost-secret
    namespace: prod
sops:
    lastmodified: "2026-02-21T17:24:15Z"
    mac: ENC[AES256_GCM,data:cvPGMoMI6+g3/aI7wvAR6G6Qjye0mnEeH+WCfI8B34/wTxY4kslOX2LSK1p2gxfVDKm/Moj0j5zFTGuwWyPT4Eqs8xFUl1s6WvBlxoI+1QHnnEp+4MbWsaRVTm0lNbyz7p3FSuVdbF9Mk2Y2Aa0vFaNA+B72w++qUFzCewcVPj0=,iv:1+SLCZrkloY18ez3ZD/BdewnAPtBaQ2nA572PbmcWvk=,tag:AqgXUJeKbWaEVoQczydz1g==,type:str]
    pgp:
        - created_at: "2026-02-21T17:24:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3/FgTUsf6UGAQ//eTa2tKhO+gPUyjwh4ZV4GNV4rH0UZfCtGn2QIhoOE+ae
            guqXOyyHv1XaNnzA4AN4Ez+J78v2IcL18KJdEN8QZpDajvzkKo3o+cpjPu+dsEof
            sJNxZjowAOPdoudjMzRv4mp7wMxGywSA2EgY8//deSvmQ7tsU4w5oF4SLZDnTNSX
            j3/5pkCMak4kwqnl+VFQUy+sxesW4K4/3a5EcH3dt9csPS0O86wa308UWqHk9sUq
            sVGg6V152eNvrcfNYvjLEK5T5EL1Ca9mDDr3NrOL/b2JCDrF0KuoOjeR6LGPcWhX
            cMABeQXLCg0gadCgfq25RAznM/e9aMPlUgTV18oGJEMX238dkuMj8Bjws5u3JUXo
            5TOYnFE8ncKf3a8u3JrNYasnFwAAKpqDhuTN9IW73bOZ9H+MOZ0u6ImcjWpX4E0l
            5rn0j1cQdAa6ZWEWmCBcJ88I2fnxaYqZ+DwuIMDNDj4tciJ3oIC3D/FQGw4kvReL
            YuiHmmjmwuWcGcCRPltomccHELNCHfERGylOqyHk4LZxgBLeGmaG/sY4H0ZXuCE9
            59BYcF+d3zyC82cxRiOkci4+10Gkqrbz46p4N/nAHlxnXiuiBAxRL7q9KpkZ+mhs
            H31VBFILo7Pch9PP2RqctHBSOmmVfqk1NXXa2LHYCuj06qpDuV7I0ecbzAnGBsXS
            XgHhpBfvMh7rhsv1KrqIJidghmefj+wOoWQGa0AIaqTXxLPJ5AeE8x9q9SFImBfU
            wnZ7SsWpBpML2m/Peik0gZzor/bAJCGE4KGcOu6kXP4SaEbaIheWagwwJZQiWMk=
            =sntD
            -----END PGP MESSAGE-----
          fp: 78C2A5FEEC0770BC8642B9D40BD469E85A8146CD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
