apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docmost/docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: docmost
  name: docmost
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: docmost
